name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev
    - name: make
      run: make
    - name: make check
      run: make check
